name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: install dnsmasq
      run: apt update && apt install -y dnsmasq

    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: run tests
      run: go test ./... -v -race

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: build binary
      run: go build
    - uses: https://github.com/actions/upload-artifact@v3
      with:
        name: dnsmasq_exporter
        path: dnsmasq_exporter
